version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shrtdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shrt@admin.com
      PGADMIN_DEFAULT_PASSWORD: shrtadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - ./.env
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - postgres
      - server
    ports:
      - "3000:3000"
    restart: always
volumes:
  postgres-data:
  pgadmin-data:
